import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="antialiased">
        <div className="min-h-screen bg-gray-50">
          <div className="container mx-auto p-6 max-w-6xl">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
