import { ThemeProvider } from 'next-themes';

import './globals.css';
import { HeaderContainer } from './_containers/header';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="min-h-screen">
            <HeaderContainer />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
