import { ThemeProvider } from 'next-themes';

import './globals.css';
import { HeaderContainer } from './_containers/header';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="flex min-h-screen flex-col">
            <HeaderContainer />
            <div className="flex-1">{children}</div>
            <footer className="py-4 text-center text-xs leading-5">
              当サイトは非公式のファンサイトです。
              <br />
              ポケモンおよび関連する画像・名称等の著作権・商標権は、
              <a
                href="https://www.pokemon.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-500 hover:underline"
              >
                ポケモン
              </a>
              、
              <a
                href="https://www.nintendo.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-500 hover:underline"
              >
                任天堂
              </a>
              、
              <a
                href="https://www.gamefreak.co.jp"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-500 hover:underline"
              >
                ゲームフリーク
              </a>
              、
              <a
                href="https://www.creatures.co.jp"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-500 hover:underline"
              >
                クリーチャーズ
              </a>
              に帰属します。
              <br />
              スプライト画像は
              <a
                href="https://komori541milk.web.fc2.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-500 hover:underline"
              >
                転寝（こもり）みるく
              </a>
              様よりご許可をいただき利用しています。
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
